# contains all functions up to MPi 3.1
def get_version_dict():
    return {'MPI_Abort': '1.0', 'MPI_Accumulate': '2.0', 'MPI_Add_error_class': '2.0', 'MPI_Add_error_code': '2.0',
            'MPI_Add_error_string': '2.0', 'MPI_Address': '1.0', 'MPI_Allgather': '1.0', 'MPI_Allgatherv': '1.0',
            'MPI_Alloc_mem': '2.0', 'MPI_Allreduce': '1.0', 'MPI_Alltoall': '1.0', 'MPI_Alltoallv': '1.0',
            'MPI_Alltoallw': '2.0', 'MPI_Attr_delete': '1.0', 'MPI_Attr_get': '1.0', 'MPI_Attr_put': '1.0',
            'MPI_Barrier': '1.0', 'MPI_Bcast': '1.0', 'MPI_Bsend': '1.0', 'MPI_Bsend_init': '1.0',
            'MPI_Buffer_attach': '1.0', 'MPI_Buffer_detach': '1.0', 'MPI_Cancel': '1.0', 'MPI_Cart_coords': '1.0',
            'MPI_Cart_create': '1.0', 'MPI_Cart_get': '1.0', 'MPI_Cart_map': '1.0', 'MPI_Cart_rank': '1.0',
            'MPI_Cart_shift': '1.0', 'MPI_Cart_sub': '1.0', 'MPI_Cartdim_get': '1.0', 'MPI_Close_port': '2.0',
            'MPI_Comm_accept': '2.0', 'MPI_Comm_c2f': '2.0', 'MPI_Comm_call_errhandler': '2.0',
            'MPI_Comm_compare': '1.0', 'MPI_Comm_connect': '2.0', 'MPI_Comm_create': '1.0',
            'MPI_Comm_create_errhandler': '2.0', 'MPI_Comm_create_group': '3.0', 'MPI_Comm_create_keyval': '2.0',
            'MPI_Comm_delete_attr': '2.0', 'MPI_Comm_disconnect': '2.0', 'MPI_Comm_dup': '1.0',
            'MPI_Comm_dup_with_info': '3.0', 'MPI_Comm_f2c': '2.0', 'MPI_Comm_free': '1.0',
            'MPI_Comm_free_keyval': '2.0', 'MPI_Comm_get_attr': '2.0', 'MPI_Comm_get_errhandler': '2.0',
            'MPI_Comm_get_info': '3.0', 'MPI_Comm_get_name': '2.0', 'MPI_Comm_get_parent': '2.0',
            'MPI_Comm_group': '1.0', 'MPI_Comm_idup': '3.0', 'MPI_Comm_join': '2.0', 'MPI_Comm_rank': '1.0',
            'MPI_Comm_remote_group': '1.0', 'MPI_Comm_remote_size': '1.0', 'MPI_Comm_set_attr': '2.0',
            'MPI_Comm_set_errhandler': '2.0', 'MPI_Comm_set_info': '3.0', 'MPI_Comm_set_name': '2.0',
            'MPI_Comm_size': '1.0', 'MPI_Comm_spawn': '2.0', 'MPI_Comm_spawn_multiple': '2.0', 'MPI_Comm_split': '1.0',
            'MPI_Comm_split_type': '3.0', 'MPI_Comm_test_inter': '1.0', 'MPI_Compare_and_swap': '3.0',
            'MPI_Dims_create': '1.0', 'MPI_Dist_graph_create': '2.2', 'MPI_Dist_graph_create_adjacent': '2.2',
            'MPI_Dist_graph_neighbors': '2.2', 'MPI_Dist_graph_neighbors_count': '2.2', 'MPI_Errhandler_create': '1.0',
            'MPI_Errhandler_free': '1.0', 'MPI_Errhandler_get': '1.0', 'MPI_Errhandler_set': '1.0',
            'MPI_Error_class': '1.0', 'MPI_Error_string': '1.0', 'MPI_Exscan': '2.0', 'MPI_Fetch_and_op': '3.0',
            'MPI_File_c2f': '2.0', 'MPI_File_call_errhandler': '2.0', 'MPI_File_close': '2.0',
            'MPI_File_create_errhandler': '2.0', 'MPI_File_delete': '2.0', 'MPI_File_f2c': '2.0',
            'MPI_File_get_amode': '2.0', 'MPI_File_get_atomicity': '2.0', 'MPI_File_get_byte_offset': '2.0',
            'MPI_File_get_errhandler': '2.0', 'MPI_File_get_group': '2.0', 'MPI_File_get_info': '2.0',
            'MPI_File_get_position': '2.0', 'MPI_File_get_position_shared': '2.0', 'MPI_File_get_size': '2.0',
            'MPI_File_get_type_extent': '2.0', 'MPI_File_get_view': '2.0', 'MPI_File_iread': '2.0',
            'MPI_File_iread_all': '3.1', 'MPI_File_iread_at': '2.0', 'MPI_File_iread_at_all': '3.1',
            'MPI_File_iread_shared': '2.0', 'MPI_File_iwrite': '2.0', 'MPI_File_iwrite_all': '3.1',
            'MPI_File_iwrite_at': '2.0', 'MPI_File_iwrite_at_all': '3.1', 'MPI_File_iwrite_shared': '2.0',
            'MPI_File_open': '2.0', 'MPI_File_preallocate': '2.0', 'MPI_File_read': '2.0', 'MPI_File_read_all': '2.0',
            'MPI_File_read_all_begin': '2.0', 'MPI_File_read_all_end': '2.0', 'MPI_File_read_at': '2.0',
            'MPI_File_read_at_all': '2.0', 'MPI_File_read_at_all_begin': '2.0', 'MPI_File_read_at_all_end': '2.0',
            'MPI_File_read_ordered': '2.0', 'MPI_File_read_ordered_begin': '2.0', 'MPI_File_read_ordered_end': '2.0',
            'MPI_File_read_shared': '2.0', 'MPI_File_seek': '2.0', 'MPI_File_seek_shared': '2.0',
            'MPI_File_set_atomicity': '2.0', 'MPI_File_set_errhandler': '2.0', 'MPI_File_set_info': '2.0',
            'MPI_File_set_size': '2.0', 'MPI_File_set_view': '2.0', 'MPI_File_sync': '2.0', 'MPI_File_write': '2.0',
            'MPI_File_write_all': '2.0', 'MPI_File_write_all_begin': '2.0', 'MPI_File_write_all_end': '2.0',
            'MPI_File_write_at': '2.0', 'MPI_File_write_at_all': '2.0', 'MPI_File_write_at_all_begin': '2.0',
            'MPI_File_write_at_all_end': '2.0', 'MPI_File_write_ordered': '2.0', 'MPI_File_write_ordered_begin': '2.0',
            'MPI_File_write_ordered_end': '2.0', 'MPI_File_write_shared': '2.0', 'MPI_Finalize': '1.0',
            'MPI_Finalized': '2.0', 'MPI_Free_mem': '2.0', 'MPI_Gather': '1.0', 'MPI_Gatherv': '1.0', 'MPI_Get': '2.0',
            'MPI_Get_accumulate': '3.0', 'MPI_Get_address': '2.0', 'MPI_Get_count': '1.0', 'MPI_Get_elements': '1.0',
            'MPI_Get_elements_x': '3.0', 'MPI_Get_library_version': '3.0', 'MPI_Get_processor_name': '1.0',
            'MPI_Get_version': '1.0', 'MPI_Graph_create': '1.0', 'MPI_Graph_get': '1.0', 'MPI_Graph_map': '1.0',
            'MPI_Graph_neighbors': '1.0', 'MPI_Graph_neighbors_count': '1.0', 'MPI_Graphdims_get': '1.0',
            'MPI_Grequest_complete': '2.0', 'MPI_Grequest_start': '2.0', 'MPI_Group_c2f': '2.0',
            'MPI_Group_compare': '1.0', 'MPI_Group_difference': '1.0', 'MPI_Group_excl': '1.0', 'MPI_Group_f2c': '2.0',
            'MPI_Group_free': '1.0', 'MPI_Group_incl': '1.0', 'MPI_Group_intersection': '1.0',
            'MPI_Group_range_excl': '1.0', 'MPI_Group_range_incl': '1.0', 'MPI_Group_rank': '1.0',
            'MPI_Group_size': '1.0', 'MPI_Group_translate_ranks': '1.0', 'MPI_Group_union': '1.0',
            'MPI_Iallgather': '3.0', 'MPI_Iallgatherv': '3.0', 'MPI_Iallreduce': '3.0', 'MPI_Ialltoall': '3.0',
            'MPI_Ialltoallv': '3.0', 'MPI_Ialltoallw': '3.0', 'MPI_Ibarrier': '3.0', 'MPI_Ibcast': '3.0',
            'MPI_Ibsend': '1.0', 'MPI_Iexscan': '3.0', 'MPI_Igather': '3.0', 'MPI_Igatherv': '3.0',
            'MPI_Improbe': '3.0', 'MPI_Imrecv': '3.0', 'MPI_Ineighbor_allgather': '3.0',
            'MPI_Ineighbor_allgatherv': '3.0', 'MPI_Ineighbor_alltoall': '3.0', 'MPI_Ineighbor_alltoallv': '3.0',
            'MPI_Ineighbor_alltoallw': '3.0', 'MPI_Info_c2f': '2.0', 'MPI_Info_create': '2.0', 'MPI_Info_delete': '2.0',
            'MPI_Info_dup': '2.0', 'MPI_Info_f2c': '2.0', 'MPI_Info_free': '2.0', 'MPI_Info_get': '2.0',
            'MPI_Info_get_nkeys': '2.0', 'MPI_Info_get_nthkey': '2.0', 'MPI_Info_get_valuelen': '2.0',
            'MPI_Info_set': '2.0', 'MPI_Init': '1.0', 'MPI_Init_thread': '2.0', 'MPI_Initialized': '1.0',
            'MPI_Intercomm_create': '1.0', 'MPI_Intercomm_merge': '1.0', 'MPI_Iprobe': '1.0', 'MPI_Irecv': '1.0',
            'MPI_Ireduce': '3.0', 'MPI_Ireduce_scatter': '3.0', 'MPI_Ireduce_scatter_block': '3.0', 'MPI_Irsend': '1.0',
            'MPI_Is_thread_main': '2.0', 'MPI_Iscan': '3.0', 'MPI_Iscatter': '3.0', 'MPI_Iscatterv': '3.0',
            'MPI_Isend': '1.0', 'MPI_Issend': '1.0', 'MPI_Keyval_create': '1.0', 'MPI_Keyval_free': '1.0',
            'MPI_Lookup_name': '2.0', 'MPI_Mprobe': '3.0', 'MPI_Mrecv': '3.0', 'MPI_Neighbor_allgather': '3.0',
            'MPI_Neighbor_allgatherv': '3.0', 'MPI_Neighbor_alltoall': '3.0', 'MPI_Neighbor_alltoallv': '3.0',
            'MPI_Neighbor_alltoallw': '3.0', 'MPI_Op_c2f': '2.0', 'MPI_Op_commutative': '2.2', 'MPI_Op_create': '1.0',
            'MPI_Op_f2c': '2.0', 'MPI_Op_free': '1.0', 'MPI_Open_port': '2.0', 'MPI_Pack': '1.0',
            'MPI_Pack_external': '2.0', 'MPI_Pack_external_size': '2.0', 'MPI_Pack_size': '1.0', 'MPI_Pcontrol': '1.0',
            'MPI_Probe': '1.0', 'MPI_Publish_name': '2.0', 'MPI_Put': '2.0', 'MPI_Query_thread': '2.0',
            'MPI_Raccumulate': '3.0', 'MPI_Recv': '1.0', 'MPI_Recv_init': '1.0', 'MPI_Reduce': '1.0',
            'MPI_Reduce_local': '2.2', 'MPI_Reduce_scatter': '1.0', 'MPI_Reduce_scatter_block': '2.2',
            'MPI_Register_datarep': '2.0', 'MPI_Request_c2f': '2.0', 'MPI_Request_f2c': '2.0',
            'MPI_Request_free': '1.0', 'MPI_Request_get_status': '2.0', 'MPI_Rget': '3.0', 'MPI_Rget_accumulate': '3.0',
            'MPI_Rput': '3.0', 'MPI_Rsend': '1.0', 'MPI_Rsend_init': '1.0', 'MPI_Scan': '1.0', 'MPI_Scatter': '1.0',
            'MPI_Scatterv': '1.0', 'MPI_Send': '1.0', 'MPI_Send_init': '1.0', 'MPI_Sendrecv': '1.0',
            'MPI_Sendrecv_replace': '1.0', 'MPI_Sizeof': '2.0', 'MPI_Ssend': '1.0', 'MPI_Ssend_init': '1.0',
            'MPI_Start': '1.0', 'MPI_Startall': '1.0', 'MPI_Status_c2f': '2.0', 'MPI_Status_f2c': '2.0',
            'MPI_Status_set_cancelled': '2.0', 'MPI_Status_set_elements': '2.0', 'MPI_Status_set_elements_x': '3.0',
            'MPI_Test': '1.0', 'MPI_Test_cancelled': '1.0', 'MPI_Testall': '1.0', 'MPI_Testany': '1.0',
            'MPI_Testsome': '1.0', 'MPI_Topo_test': '1.0', 'MPI_Type_c2f': '2.0', 'MPI_Type_commit': '1.0',
            'MPI_Type_contiguous': '1.0', 'MPI_Type_create_darray': '2.0', 'MPI_Type_create_f90_complex': '2.0',
            'MPI_Type_create_f90_integer': '2.0', 'MPI_Type_create_f90_real': '2.0', 'MPI_Type_create_hindexed': '2.0',
            'MPI_Type_create_hindexed_block': '3.0', 'MPI_Type_create_hvector': '2.0',
            'MPI_Type_create_indexed_block': '2.0', 'MPI_Type_create_keyval': '2.0', 'MPI_Type_create_resized': '2.0',
            'MPI_Type_create_struct': '2.0', 'MPI_Type_create_subarray': '2.0', 'MPI_Type_delete_attr': '2.0',
            'MPI_Type_dup': '2.0', 'MPI_Type_extent': '1.0', 'MPI_Type_f2c': '2.0', 'MPI_Type_free': '1.0',
            'MPI_Type_free_keyval': '2.0', 'MPI_Type_get_attr': '2.0', 'MPI_Type_get_contents': '2.0',
            'MPI_Type_get_envelope': '2.0', 'MPI_Type_get_extent': '2.0', 'MPI_Type_get_extent_x': '3.0',
            'MPI_Type_get_name': '2.0', 'MPI_Type_get_true_extent': '2.0', 'MPI_Type_get_true_extent_x': '3.0',
            'MPI_Type_hindexed': '1.0', 'MPI_Type_hvector': '1.0', 'MPI_Type_indexed': '1.0', 'MPI_Type_lb': '1.0',
            'MPI_Type_match_size': '2.0', 'MPI_Type_set_attr': '2.0', 'MPI_Type_set_name': '2.0',
            'MPI_Type_size': '1.0', 'MPI_Type_size_x': '3.0', 'MPI_Type_struct': '1.0', 'MPI_Type_ub': '1.0',
            'MPI_Type_vector': '1.0', 'MPI_Unpack': '1.0', 'MPI_Unpack_external': '2.0', 'MPI_Unpublish_name': '2.0',
            'MPI_Wait': '1.0', 'MPI_Waitall': '1.0', 'MPI_Waitany': '1.0', 'MPI_Waitsome': '1.0',
            'MPI_Win_allocate': '3.0', 'MPI_Win_allocate_shared': '3.0', 'MPI_Win_attach': '3.0', 'MPI_Win_c2f': '2.0',
            'MPI_Win_call_errhandler': '2.0', 'MPI_Win_complete': '2.0', 'MPI_Win_create': '2.0',
            'MPI_Win_detach': '3.0', 'MPI_Win_create_dynamic': '3.0', 'MPI_Win_create_errhandler': '2.0',
            'MPI_Win_create_keyval': '2.0', 'MPI_Win_delete_attr': '2.0', 'MPI_Win_f2c': '2.0', 'MPI_Win_fence': '2.0',
            'MPI_Win_free': '2.0', 'MPI_Win_free_keyval': '2.0', 'MPI_Win_get_attr': '2.0',
            'MPI_Win_get_errhandler': '2.0', 'MPI_Win_get_group': '2.0', 'MPI_Win_get_info': '3.0',
            'MPI_Win_get_name': '2.0', 'MPI_Win_lock': '2.0', 'MPI_Win_lock_all': '3.0', 'MPI_Win_post': '2.0',
            'MPI_Win_set_attr': '2.0', 'MPI_Win_set_errhandler': '2.0', 'MPI_Win_flush': '3.0',
            'MPI_Win_flush_all': '3.0', 'MPI_Win_flush_local': '3.0', 'MPI_Win_flush_local_all': '3.0',
            'MPI_Win_set_info': '3.0', 'MPI_Win_set_name': '2.0', 'MPI_Win_shared_query': '3.0', 'MPI_Win_start': '2.0',
            'MPI_Win_sync': '3.0', 'MPI_Win_test': '2.0', 'MPI_Win_unlock': '2.0', 'MPI_Win_unlock_all': '3.0',
            'MPI_Win_wait': '2.0', 'MPI_Wtick': '1.0', 'MPI_Wtime': '1.0', 'MPI_User_function': '1.0',
            'MPI_Copy_function': '1.0', 'MPI_Delete_function': '1.0', 'MPI Comm errhandler fn': '2.0',
            'MPI_Comm_copy_attr_function': '2.0', 'MPI_Comm_delete_attr_function': '2.0',
            'MPI_Grequest_query_function': '2.0', 'MPI_Grequest_free_function': '2.0',
            'MPI_Grequest_cancel_function': '2.0', 'MPI_Comm_errhandler_function': '2.2', 'MPI_DUP_FN': '2.2',
            'MPI_T_pvar_handle_alloc': '3.0', 'MPI_T_pvar_start': '3.0', 'MPI_T_pvar_read': '3.0',
            'MPI_T_pvar_write': '3.0', 'MPI_T_pvar_reset': '3.0', 'MPI_T_pvar_readreset': '3.0',
            'MPI_T_category_get_num': '3.0', 'MPI_T_category_get_info': '3.0', 'MPI_T_category_get_cvars': '3.0',
            'MPI_T_category_get_pvars': '3.0', 'MPI_T_category_get_categories': '3.0', 'MPI_T_category_changed': '3.0',
            'MPI_T_cvar_get_index': '3.0', 'MPI_T_pvar_get_index': '3.0', 'MPI_T_category_get_index': '3.0',
            'MPI_T_pvar_handle_free': '3.0', 'MPI_T_pvar_stop': '3.0', 'MPI_T_pvar_session_free': '3.0',
            'MPI_T_cvar_get_num': '3.0', 'MPI_T_init_thread': '3.0', 'MPI_T_pvar_session_create': '3.0',
            'MPI_T_enum_get_info': '3.0', 'MPI_T_enum_get_item': '3.0', 'MPI_T_finalize': '3.0',
            'MPI_T_cvar_get_info': '3.0', 'MPI_T_cvar_handle_alloc': '3.0', 'MPI_T_cvar_handle_free': '3.0',
            'MPI_T_cvar_read': '3.0', 'MPI_T_cvar_write': '3.0', 'MPI_T_pvar_get_num': '3.0',
            'MPI_T_pvar_get_info': '3.0', 'MPI_Aint_add': '3.1', 'MPI_Aint_diff': '3.1'}
